yext/pages

sites-config/ci.json
It was inadvertently removed in #98.
=> ci: add site-config back for Pages

README.md, packages/pages/package.json, pnpm-lock.yaml
Also update to vitepress latest version
=> docs: fix links

packages/pages/CHANGELOG.md, packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx
Updates the regex to support non-prod image urls. Fixes #164
=> fix(components): add environment compatibility to mktgcdn urls

packages/pages/CHANGELOG.md, packages/pages/src/components/image/image.tsx
=> style(image): fix linter warnings

packages/pages/CHANGELOG.md, packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx, packages/pages/src/components/image/types.ts
fixes #156, improves behavior for #155
TEST=auto
=> feat(components): add support for simple image fields

packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx
Fixes https://github.com/yext/pages/issues/194
=> fix(components): image url not using correct env in all cases

packages/plugins/index.ts, packages/plugins/slugManager/README.md, packages/plugins/slugManager/api.ts, packages/plugins/slugManager/manager.ts, packages/plugins/slugManager/mod.ts, packages/plugins/slugManager/test.ts
TEST=manual
tested in a demo account. confirmed that webhook and connector functions
successfully updated primary and alternate language profiles
=> feat(pages-plugins): add slug manager plugin

packages/pages/THIRD-PARTY-NOTICES, packages/plugins/slugManager/manager.ts
J=None
TEST=manual
- ran updated version for wells
=> fix(pages-plugins): handle json object input

packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx, packages/pages/src/components/image/types.ts
fix #223
J=SLAP-2436
TEST=auto
=> fix(components): add loading eager to image

packages/pages/src/components/address/methods.test.ts, packages/pages/src/components/address/methods.ts, packages/pages/src/components/address/types.ts
=> feat(components): make check for provider in getDirections check be case insensitive

packages/pages/src/components/address/methods.test.ts, packages/pages/src/components/address/methods.ts, packages/pages/src/components/address/types.ts
…ase insensitive (#254)
J=CR-2961
TEST=manual
=> feat(components): make check for publisher in getDirections be case-insensitive

packages/pages/src/components/address/methods.ts, packages/pages/src/components/address/types.ts
=> fix(components): add empty string fallback for when publisher is null

packages/pages/src/dev/server/middleware/constants.ts, packages/pages/src/dev/server/middleware/indexPage.ts
=> chore: add prod url message

packages/pages/src/common/src/template/internal/loader.ts
This fixes ico file imports, specifically when running `pages generate features`.
=> fix(dev): handle ico import

packages/pages/src/common/src/template/types.ts
This leverages the auto TS generation and allows users to type the document for helpful autocomplete.
=> feat(dev): support document typing

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/dev/server/autoInit.ts, pnpm-lock.yaml
The `.yextrc` CLI was updated to make the following changes. 
1. Be more descriptive, including a welcome message, a success message, and information on where to find things like Account ID and how to choose sbx vs prod. 
2. A new UI that only allows you to type numbers for Account ID and choose between sbx vs prod (less error prone).
3. `.yextrc` file now allows you to manually type in sbx, prod, qa, and dev.
=> fix(dev): qa updates for `.yextrc` CLI

packages/pages/src/dev/server/middleware/indexPage.ts, packages/pages/src/dev/server/middleware/serverRenderSlugRoute.ts
- was using decodeURI not decodeURIComponent in one spot
- encoding the URI on the index page is not necessary
=> fix(dev): fixed URI encoding issue 

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/bin/loader.js, packages/pages/src/bin/spawn.ts, packages/pages/src/common/src/template/internal/_client17.tsx, packages/pages/src/common/src/template/internal/getTemplateFilepaths.ts, packages/pages/src/components/link/link.test.tsx, packages/pages/src/dev/server/server.ts, packages/pages/src/vite-plugin/build/build.ts, playground/locations-site/package.json, playground/multibrand-site/package.json, pnpm-lock.yaml
Tested against Node 17, 18, 19 for both React 17 and 18.
=> feat(dev/plugin): support React 18

packages/pages/src/common/src/template/internal/types.test.ts, packages/pages/src/common/src/template/internal/types.ts
Due to changing direction, undid some of what shrisha did [earlier](https://github.com/yext/pages/commit/f6a71fc5667f5a081475a1c6377b7d5736e24942)
=> feat(dev): default hydrate to true

packages/pages/src/common/src/feature/features.ts
=> refactor: use nullish coalescing in features.ts

packages/pages/src/dev/server/ssr/generateTestData.ts
=> fix(dev): scope/domain omitted in dynamic mode

packages/pages/src/dev/server/middleware/serverRenderRoute.ts, packages/pages/src/dev/server/middleware/serverRenderSlugRoute.ts
=> fix(dev): server crashes instead of producing 500 error

packages/pages/src/dev/server/middleware/sendAppHTML.ts
=> fix(dev): hydration does not reflect template data mutations

packages/pages/src/common/src/function/internal/types.test.ts, packages/pages/src/common/src/function/types.ts, packages/pages/src/dev/server/middleware/serveHttpFunction.ts, packages/pages/src/dev/server/server.ts
This fixes an issue where the request body was not properly parsed and sent to the function. It also fixes async functions not working.
=> fix: async serverless functions and body parsing

packages/pages/src/dev/server/middleware/serveHttpFunction.ts
Fixes an issue where the body was coming back as an object in dev mode instead of a string.
=> fix(dev): serverless functions body format consistency

packages/plugins/slugManager/api.ts, packages/plugins/slugManager/manager.ts, packages/plugins/slugManager/test.ts
Also refactor slugFormat type.
J=CR-3203
=> fix(pages-plugins): slugManager searchIds not working on webhook update

packages/pages/src/dev/server/ssr/getLocalData.ts, packages/pages/src/dev/server/ssr/propsLoader.ts
siteInternalHostName is manually set to scope
=> feat(dev): set siteInternalHostName locally

packages/pages/THIRD-PARTY-NOTICES, packages/plugins/slugManager/manager.ts
=> feat(pages-plugins): add entity type to slug manager default field

packages/pages/src/common/src/template/internal/getTemplateFilepaths.test.ts, packages/pages/src/common/src/template/internal/getTemplateFilepaths.ts, packages/pages/src/common/src/template/internal/util.ts
Fixes https://github.com/yext/pages/issues/410
=> fix(dev/plugin): custom _client not working with React 17

packages/pages/src/dev/server/autoInit.ts
Fixes https://github.com/yext/pages/issues/448
=> fix(dev): make production the default for yextrc

packages/pages/docs/api/pages.templateconfig.alternatelanguagefields.md, packages/pages/docs/api/pages.templateconfig.md, packages/pages/etc/pages.api.md, packages/pages/src/common/src/feature/features.test.ts, packages/pages/src/common/src/feature/features.ts, packages/pages/src/common/src/feature/stream.test.ts, packages/pages/src/common/src/template/internal/types.test.ts, packages/pages/src/common/src/template/internal/types.ts, packages/pages/src/common/src/template/internal/validateTemplateModuleInternal.test.ts, packages/pages/src/common/src/template/types.ts, packages/pages/src/dev/server/ssr/findMatchingStaticTemplate.ts, packages/pages/src/dev/server/ssr/generateTestData.ts, packages/pages/src/generate/templates/createTemplatesJson.test.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.test.tsx
Adds a templateType option to TemplateModuleInternal to make it easier to filter by certain template types.
=> fix(dev): filter out static templates when determining slug fields

packages/pages/src/common/src/loader/vite.ts
Fixes https://github.com/yext/pages/issues/447
=> fix(dev): remove websocket error

packages/pages/src/vite-plugin/serverless-functions/plugin.ts
Bundling all serverless components in a single vite/rollup step does not allow you to create single outputs per entry. Chunks are always created for shared code. This changes the logic to perform a build per serverless function so that any shared code gets bundled in each corresponding output mod.ts.
=> fix(plugin): serverless function shared components

.github/workflows/semantic-pull-request.yml, packages/pages/src/upgrade/migrateConfig.test.ts, packages/pages/src/upgrade/migrateConfig.ts
The keys need to be changed from
```
reverseProxy:
displayUrlPrefix: foo
```
to
```
serving:
reverseProxyPrefix: foo
```
=> fix(upgrade): name of serving config in config.yaml

packages/pages/src/scaffold/modules/generate.ts, packages/pages/src/scaffold/modules/templates.ts
Verified that modules load much faster with the updated tailwind path and are created properly through scaffold.
=> fix(scaffold): update scaffold command to point tailwind to ./src/modules

packages/pages/src/vite-plugin/modules/plugin.ts
Tested prod, dev, dev --module, and scaffold modules commands. All work as expected.
=> fix(plugin): fixed logger error during build

packages/pages/src/scaffold/modules/templates.ts
[SUMO-5837](https://yexttest.atlassian.net/browse/SUMO-5837)
=> fix(scaffold): edit tailwind in modules templates

packages/pages/src/scaffold/modules/generate.test.ts, packages/pages/src/scaffold/modules/generate.ts, packages/pages/src/scaffold/modules/templates.test.ts, packages/pages/src/scaffold/modules/templates.ts
Fixes https://github.com/yext/pages/issues/505
=> fix(scaffold): validate + format module name from user

packages/pages/src/scaffold/modules/generate.ts
[SUMO-5836](https://yexttest.atlassian.net/browse/SUMO-5836)
=> feat(scaffold): add response headers to config.yaml during scaffold

packages/pages/src/scaffold/template/sampleTemplates.ts
This updates the scaffold template command to be consistent with recent changes.
=> fix(scaffold): update scaffold template command

packages/plugins/slugManager/manager.ts
See issue identified at https://yexttest.atlassian.net/browse/TECHOPS-12762?focusedCommentId=1586488
=> fix(pages-plugins): prevent making api request with unbounded entities

packages/pages/docs/api/pages.stream.filter.md, packages/pages/docs/api/pages.stream.md, packages/pages/etc/pages.api.md, packages/pages/src/common/src/feature/stream.ts, packages/pages/src/common/src/template/internal/types.ts, packages/pages/src/common/src/template/types.ts
When stream is defined and the template is not VE, if filter isn't set, it'll error in build
=> feat: make stream's filter optional

packages/pages/src/upgrade/migrateConfig.ts, packages/pages/src/upgrade/pagesUpdater.ts
This also attempts to fix the upgrade script sometimes hanging by removing unnecessary async functions.
=> feat(upgrade): swap sites-react-components to pages-components
