yext/pages

packages/pages/src/dev/server/middleware/serverRenderRoute.ts, packages/pages/src/dev/server/ssr/generateTestData.test.ts, packages/pages/src/dev/server/ssr/generateTestData.ts, packages/pages/src/dev/server/ssr/getLocalData.ts, packages/pages/src/dev/server/ssr/pageLoader.ts, packages/pages/src/dev/server/ssr/urlToFeature.ts
For now "en" is used as the default locale until a future enhancement is added to allow users to specify the default locale they want to use.
=> feat(dev): support alternate languages via `locale` query param

packages/pages/src/dev/server/middleware/indexPage.ts, packages/pages/src/dev/server/ssr/featureNameToTemplateModuleInternal.ts
Note that feature names with spaces currently doesn't work until https://github.com/vitejs/vite/issues/9446 is fixed.
=> fix(dev): honor feature name casing in local dev url (fixes #121)

packages/pages/src/util/env.test.ts, packages/pages/src/util/env.ts, packages/pages/src/util/index.ts
Checks if a user is on a production domain client-side. Useful for firing analytics only in a real production environment.
=> feat(util): add isProduction function

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx, packages/pages/src/components/image/index.ts, packages/pages/src/components/image/types.ts, packages/pages/src/components/index.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.test.tsx, pnpm-lock.yaml
This PR sets up the components/ export and adds an Image component.
J=SUMO-4687
TEST=manual
Ran against both dev and production builds on the starter repo, made sure I can import the Image component and all functionalities work as specified [here](https://www.notion.so/Images-c04403f8e8f14e7bb3869894d5a4860b).
=> feat(components): add `Image` component

packages/pages/src/dev/server/middleware/finalSlashRedirect.test.ts, packages/pages/src/dev/server/middleware/finalSlashRedirect.ts, packages/pages/src/dev/server/server.ts
If the local dev url ends in a slash, 301 redirects to the canonical url without the slash. This will prevent future issues when people use relative links.
=> feat(dev): redirect if url ends in final slash (closes #143)

packages/pages/CHANGELOG.md, packages/pages/src/util/runtime.test.ts, packages/pages/src/util/runtime.ts
We noticed a bug where our getRuntime function makes the
assumption that a global window object will be available.
This will not be true when running in the plugins system
and will cause page generation to fail.
TEST=auto,manual
Updated unit tests. Tested locally to make sure getRuntime
still returns the expected results for node, deno, and
browser.
=> fix: update getRuntime to work with the plugins system

packages/pages/src/dev/server/ssr/generateTestData.ts, packages/pages/src/dev/server/ssr/pageLoader.ts
Fixes #168 by catching the json parse error and returning null, which prompts the server to return an error.
It will still 500, when a 404 would _probably_ be preferable, but at least the server will not crash now.
=> fix(dev): prevent crashing on empty id

.github/workflows/semantic-pull-request.yml
Some changes affect both the plugin and dev mode. This adds this as a valid scope.
=> chore: add dev/plugin as title option

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/components/analytics/Analytics.ts, packages/pages/src/components/analytics/analytics.test.tsx, packages/pages/src/components/analytics/context.ts, packages/pages/src/components/analytics/helpers.ts, packages/pages/src/components/analytics/hooks.ts, packages/pages/src/components/analytics/index.ts, packages/pages/src/components/analytics/interfaces.ts, packages/pages/src/components/analytics/provider.tsx, packages/pages/src/components/analytics/scope.tsx, packages/pages/src/components/index.ts, pnpm-lock.yaml
Adds new AnalyticsProvider and AnalyticsScope components for sending events to the Yext Analytics system.
=> feat(components): add AnalyticsProvider

packages/pages/CHANGELOG.md, packages/pages/src/common/src/template/internal/loader.test.ts, packages/pages/src/common/src/template/internal/loader.ts
Fixes: https://github.com/yext/pages/issues/176
A [PR](https://github.com/yext/pages/pull/170) which adjusted how template modules were imported was shipped after a [change](https://github.com/yext/pages/pull/173) which fixed up some issues running pagesJS on Windows machines.
Critically, one of the fixes was to ensure that file urls were being used to dynamically import template modules. #170 moved some files but missed the change from #173 so dynamic import change was lost -- thus breaking the import again on Windows machines.
This change fixes things.
=> fix(dev): fix template path import for windows

packages/pages/src/components/README.md, packages/pages/src/components/analytics/Analytics.ts, packages/pages/src/components/analytics/analytics.test.tsx, packages/pages/src/components/analytics/hooks.ts, packages/pages/src/components/analytics/interfaces.ts, packages/pages/src/components/index.ts, packages/pages/src/components/link/index.ts, packages/pages/src/components/link/link.test.tsx, packages/pages/src/components/link/link.tsx, packages/pages/src/components/link/methods.test.ts, packages/pages/src/components/link/methods.ts, packages/pages/src/components/link/types.ts, pnpm-lock.yaml
Summary of changes from the existing Consulting version of this component, mainly for @tatimblin: 
* I converted the LinkType to a const rather than an enum so that users can either import the value, or pass a raw string. Follows the pattern used by the `layout` prop on the Image, which came out of a slack discussion.
* The component defines its own CTA type, in the type I made `label` optional and changed its type from string to ReactNode so that it's easier to use things like icons. 
* I removed the global props for now, since I think that's probably worth a separate PR to make sure we feel good about how it works in a public repo
* I removed the phone number library. It was only used for trying to autodetect phone numbers, and I'm not sure it's worth the cost of the dependency size
* I …
=> feat(components): add Link component

packages/pages/src/vite-plugin/build/closeBundle/closeBundle.ts
Prior work was done to extract features.json generation from the build plugin. Unfortunately this is causing problems to run as a separate `pages` command in the YextCI system due to the experimental node flag required (which is actually only needed for the dev command). In order to avoid the issue in the meantime so we can unblock people and cut new releases, add the features generation back to the build as it was beforehand. Users can still generate features.json themselves though.
=> fix(plugin): add features.json generation back to build plugin

packages/pages/src/components/analytics/hooks.ts
The setAnalyticsOptIn function was being added to the window by
the AnalyticsProvider regardless of the runtime, causing 500 errors.
The window object can only be reliably accessed when gated by a
getRuntime().name === "browser" check.
We need further research on how to test all components for respecting
run time dependent functionality.
After some additional research, it does not appear that there is a good
solution for asserting that a component should not fail to render server
side.  
Some threads:
https://github.com/testing-library/react-testing-library/issues/561
https://github.com/testing-library/react-testing-library/issues/1080
J=none
TEST=none
=> fix(components): fix un-gated window access in analytics component

packages/pages/CHANGELOG.md, packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx
Should no longer forcibly convert urls to use `/p/` when they want `/p-<env>/`
=> fix(components): image url now correctly handles envs

packages/pages/CHANGELOG.md, packages/pages/src/util/runtime.test.ts, packages/pages/src/util/runtime.ts
Adds a new field to `Runtime` which indicates whether the runtime is server-side or not. This improves upon the current way of checking this which would be to do `getRuntime().name === "node" || getRuntime().name === "deno"`.
J=none
TEST=auto
=> feat(util): add isServerSide to getRuntime

packages/pages/src/components/address/index.ts, packages/pages/src/components/address/methods.test.ts, packages/pages/src/components/address/methods.ts, packages/pages/src/components/address/types.ts, packages/pages/src/components/hours/sampleData.ts
power 'Get Directions' CTAs. This function follows a hierarchy of methods to derive an entities map url, starting with using the GMB id managed by Listings. There are two TODOs which would align us completely with classic pages behviour once we know more about how a GMB/streams data structure, this shouldn't be considered blocking.
J=CR-2816
=> feat(components): add getDirections function

packages/pages/src/dev/server/middleware/indexPage.ts
This was causing unnecessary 301s after clicking the link to a static page.
=> fix(dev): remove final slash from static page urls on index

packages/pages/src/components/analytics/provider.tsx
Addresses issue #206. 
J=SLAP-2383
TEST=manual
Tested the following scenarios:
- During local development, Analytics debugging statements appeared.
- During local development, if I set `enableDebugging` to false, debugging statements did not appear.
- During production, debugging statements did not appear.
- During production, if `enableDebugging` was set to true, debugging statements appeared.
=> feat(components): enable debugging for Analytics in dev mode

packages/pages/src/bin/pages.sh
When using a top-level await to dynamically import a module in a template, `npm run features` was failing with cjs errors. This was due to [module-from-string](https://www.npmjs.com/package/module-from-string) requiring `--experimental-vm-modules` in order to work properly.
=> fix: features command when using top-level await

packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx
Fixes #209. 
J=SLAP-2384
TEST=auto, manual
Added unit tests to check that the `sizes` string is generated correctly. Also, tested locally to make sure `sizes` and `srcset` work together as expected to only make network requests to the image URL corresponding with the screen width.
=> fix(components): set sizes attribute for images

packages/plugins/slugManager/manager.ts
pagination incorrectly used a 'pagination_token' query param rather than 'pageToken'
TEST=manual
=> fix(plugin): fix slug connector pagination

packages/pages/src/components/analytics/provider.tsx
Trying to perform optional chaining on the `process` object was causing an error during generation.
TEST=none
=> fix(components): remove `process?` optional chaining

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/components/analytics/Analytics.ts, packages/pages/src/components/analytics/interfaces.ts, packages/pages/src/components/analytics/provider.tsx, pnpm-lock.yaml
Resolves #229. Bumps the version of `@yext/analytics` and adds support for passing in the `pageDomain` as a prop to the `AnalyticsProvider`, which is passed to `providePagesAnalytics`.
J=SLAP-2402
TEST=manual
Tested locally to make sure the `pageDomain` could be set from the `AnalyticsProvider` props and was only sent as a query param when formatted correctly (included the scheme). Otherwise, a console warning was logged and it was not sent in the analytics API requests.
=> feat(components): support pageDomain param

packages/pages/THIRD-PARTY-NOTICES, packages/pages/src/components/image/image.test.tsx, packages/pages/src/components/image/image.tsx, packages/pages/src/components/image/types.ts
Fixes #195.
J=SLAP-2400
TEST=auto, manual
See that the updated Jest test passes and tested locally to make sure a `width` could be specified without a `height` and vice versa when the image had a fixed layout. Specifying neither `width` nor `height` or invalid values for either still logged an error, as did specifying either a `width` or `height` (or both) when the image layout was not fixed.
=> fix(components): make fixed Image width and height optional

packages/pages/src/components/README.md, packages/pages/src/components/index.ts, packages/pages/src/components/locationmap/index.ts, packages/pages/src/components/locationmap/locationmap.stories.tsx, packages/pages/src/components/locationmap/locationmap.test.tsx, packages/pages/src/components/locationmap/locationmap.tsx, packages/pages/src/components/locationmap/types.ts
This PR adds the `LocationMap` component, which allows uses to easily add a single marker to the map and have it link to another page on marker click. The common use case for this is adding it to a location page and having the pin click link out to the directions.
=> feat(components): add `LocationMap` component

packages/pages/src/dev/server/ssr/constants.ts, packages/pages/src/dev/server/ssr/generateTestData.test.ts, packages/pages/src/dev/server/ssr/generateTestData.ts, packages/pages/tests/fixtures/cli_boilerplate.ts, packages/pages/tests/fixtures/cli_stream_data.ts, packages/pages/tests/fixtures/feature_config.ts
The `alternateLanguageFields` feature requires multiple documents to be queried, so the locale cannot be included when using that feature. Additionally since the `alternateLanguageFields` feature uses information from multiple documents (languages), multiple documents will be returned. `parseConcatenatedDocuments()` will transform the output of multiple consecutive documents into an array so that it can be searched by locale for the proper document.
fix #228
J=SLAP-2401
TEST=auto,manual
successfully served multi-lang site with alternateLanguageFields feature enabled and disabled
=> fix(dev): parse multiple stream documents

packages/pages/src/bin/pages.ts, packages/pages/src/build/build.ts, packages/pages/src/common/src/project/structure.ts, packages/pages/src/vite-plugin/plugin.ts
Vite CLI does not allow user to pass non-vite arguments (github discussions: [[1](https://github.com/vitejs/vite/issues/7065)][[2](https://github.com/vitejs/vite/pull/1188)][[3](https://github.com/vitejs/vite/issues/2891)]) -- it will throw an error for unorganized options. The recommended approach in these github discussions is to use environment variable to pass flags or info to custom vite plugins.
This PR added a new pages command: `build`, which will accepts a `scope` option for multibrand setup. Internally, it will set  an env var `YEXT_PAGES_SCOPE` and executes `vite build`. In our pages vite plugin construction, the `scope` value store in env var will be use to construct the `ProjectStructure` object.
J=SLAP-2413
TEST=manual
tested the following commands in a [test …
=> feat(dev/plugin): add build command with scope flag

packages/pages/src/common/src/template/internal/loader.ts, packages/pages/src/dev/server/middleware/serverRenderSlugRoute.ts, packages/pages/src/dev/server/ssr/generateTestData.ts
It appears we can't use loadTemplateModules() in dev mode. If we try to do so we lose support for importing .ico files (and I imagine other kinds of loaders too).
Instead, calling loadTemplateModule() (which is not used in loadTemplateModules()) in a loop works since it relies on vite to import modules.
J=[SlackThread](https://yext.slack.com/archives/C016ZKY42CF/p1668696423830079?thread_ts=1668627719.720419&cid=C016ZKY42CF)
TEST=manual
tested that I can import .ico favicons in the pages react starter, both dev mode and prod mode (yext pages generate -> yext pages serve) work
=> fix(dev): add back favicon support in dev mode

.github/workflows/build.yml, .github/workflows/publish.yml, .github/workflows/semantic-pull-request.yml, .github/workflows/third_party_notices_check.yml, .github/workflows/unit_test.yml
Upgrade GitHub actions (`pnpm/action-setup`, `amannn/action-semantic-pull-request`, and `EndBug/add-and-commit`) to remove all deprecation warnings from the workflows. These warnings were for the deprecation of [Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) and for the `set-output` and `save-state` [commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
J=SLAP-2427
TEST=manual
Test in this PR as well as #260 and #261. See that the warnings are no longer present. Note: the linting workflow will still show warnings until this PR is merged in.
=> chore: update GH workflows to remove deprecation warnings

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/dev/dev.ts, packages/pages/src/dev/server/middleware/constants.ts, packages/pages/src/dev/server/middleware/indexPage.ts, packages/pages/src/dev/server/server.ts, pnpm-lock.yaml
Update pages dev command to use new port if the default port 5173 is already occupied.
J=SLAP-2461
TEST=manual
- run `pages dev` and see that the default port is used as normal.
- run `npx serve -p 5173` to occupy the default port. Then run `pages dev` and see that a random available port is use (instead of erroring out and exit like before), and the info text also display the new port.
=> feat(dev): use new available port if default dev server port is occupied

packages/pages/src/dev/server/middleware/constants.ts
This page is intended to 404 until January release
J=[SLAP-2449](https://yexttest.atlassian.net/browse/SLAP-2449)
TEST=none
=> docs(util): update documentation url

packages/pages/src/components/link/link.test.tsx, packages/pages/src/components/link/link.tsx
The `trackClick` Analytics call in `Link` is now wrapped in a try-catch block. So, if there's an issue reporting Analytics, we will still invoke the `onCall` method.
J=SLAP-2509
TEST=auto
=> feat: gracefully handle Analytics failures in the `Link` Component.

.github/workflows/acceptance_test.yml, packages/pages/package.json, packages/pages/src/bin/spawn.ts, packages/pages/src/components/hours/hours.test.tsx, packages/pages/src/components/hours/sampleData.ts, packages/pages/src/dev/server/middleware/sendAppHTML.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.ts
file extensions are required for relative imports but not for node_modules. react-dom/server is unique because it is a node_modules import, but it references a specific file. This is fine in Node 16-18, but errors in Node 19. This item fixes support for Node 19
J=SLAP-2501
TEST=manual
successfully served the site using Node 16, 17, 18, and 19
=> chore(dev/plugin): add file extension to node_module/file import

packages/pages/src/dev/server/middleware/indexPage.ts, packages/pages/src/dev/server/public/index.html, packages/pages/src/dev/server/ssr/getPluginFileMap.ts
Parse `pluginFileMap.json` and list the resulting serverless HTTP functions on the local dev index page.
J=SLAP-2568
TEST=manual
Point the locations starter to a local pack of PagesJS and see that all HTTP functions with paths are listed on the index page, and no event-driven functions.
=> feat(dev): list serverless functions on index page

packages/pages/src/vite-plugin/build/closeBundle/closeBundle.ts, packages/pages/src/vite-plugin/build/closeBundle/functionMetadata.ts
This PR adds a step to the vite-plugin's `build` command (i.e. `pages build`) to generate `functionMetadata.json`. This file contains a mapping of the files in the `functions` directory to the names of the functions that are their default exports. If there is no top-level `functions` directory, `functionMetadata.json` is not generated.
J=SLAP-2625
TEST=manual
Point the locations starter to a local pack of PagesJS and see that the file is correctly generated when there is a `functions` directory, and is not generated if there is no `functions` directory.
=> feat(plugin): generate functionMetadata.json

packages/pages/src/vite-plugin/build/closeBundle/functionMetadata.ts
Updated the generation logic for the `functionMetadata.json` file. Now, if there's a file without a `default` export, we log an error in the console that includes the file name. 
J=SLAP-2658
TEST=manual
=> feat(plugin): update `functionMetadata` generation logic

packages/pages/src/dev/server/middleware/serverRenderSlugRoute.ts
A German partner was running into an issue with local PagesJS development. The slug field values for a number of their locations contained special, German characters. When navigating to an entity page with such a slug, the resultant `generate-test-data` command would fail. An example slug would be something like:
thüringen/gotha/harjesstraße-5
In `serverRenderSlugRoute`, we were re-constructing the slug value using an encoded version of the URL. That is, instead of the value being the above, PagesJS computed it to be:
th%C3%BCringen/gotha/harjesstra%C3%9Fe-5
This URL-encoded slug was then passed directly to `generate-test-data`, which could obviously find no corresponding entity. In this PR, I fixed the re-construction of the slug to ensure that it never includes any URL-encoding. I also …
=> fix(dev): properly support slugs with URL-encoded characters

packages/pages/src/vite-plugin/build/closeBundle/closeBundle.ts
Before this change a step in the build process could fail but because it didn't throw the YextCI build system would view it as successful, leading to confusion. If any step has an error we now throw so it's clear what happened and won't make its way to the Generation phase.
=> feat(plugin): fail the build when there are errors

packages/pages/src/generate/ci/ci.test.ts, packages/pages/src/generate/ci/ci.ts
A space in the name causes issues during `yext pages render`.
=> fix(plugin): remove space from pluginName

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/common/src/template/paths.ts, packages/pages/src/vite-plugin/build/build.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/wrapper.ts, packages/pages/src/vite-plugin/plugin.ts, pnpm-lock.yaml
Importing "path" was failing builds. Use vite-plugin-node-polyfills to handle it.
Note: Previously we tried to mark node:path as external to make it work properly for Deno, but this is currently blocked in the Yext platform.
=> fix(plugin): use vite-plugin-node-polyfills

packages/pages/package.json, packages/pages/src/components/README.md, packages/pages/src/components/map/clusterer.tsx, packages/pages/src/components/map/index.ts, packages/pages/src/components/map/map.test.tsx, packages/pages/src/components/map/map.tsx, packages/pages/src/components/map/marker.tsx, packages/pages/src/components/map/types.ts
This PR adds the `Clusterer` component, which allows users to cluster their `Marker` components when they are close together at a zoom level given the cluster radius.
Implements #279.
=> feat(components): add Clusterer component.

packages/pages/src/common/src/template/hydration.ts, packages/pages/src/dev/server/middleware/sendAppHTML.ts, packages/pages/src/vite-plugin/build/build.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/wrapper.ts
Use import paths relative to the domain rather than the filesystem. This allows reverse proxies to work, including those using a subfolder.
=> feat(plugin): add reverse proxy support

package.json, packages/pages/src/dev/dev.ts, packages/pages/src/dev/server/autoInit.ts, packages/pages/src/vite-plugin/build/build.ts, playground/locations-site/playwright.config.ts, playground/locations-site/sites-config/features.json, playground/multibrand-site/playwright.config.ts, playground/multibrand-site/sites-config/sunglasses.oakley.com/features.json, pnpm-lock.yaml
When `pages dev` is run, it will look for a `.yextrc` file (formatted in YAML). If present, it will parse out `businessId` and `universe` and run `yext init [businessId] -u [universe]`. If a `.yextrc` file is not found, it asks the user for their businessID and a universe, creates the `.yextrc` file, and runs the `yext init` command.
Has basic checking both for command line and when reading the `.yextrc` file to make sure that the businessId is a number and that universe string is valid. On error when running `yext init`, the error is logged to the console.
=> feat(dev): add .yextrc support for auto yext init

packages/pages/src/vite-plugin/build/build.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/wrapper.ts
`relativePathToRoot` was missing in some places. This also sets the Vite `base` to always be relative instead of root so users don't have to configure it.
=> fix(plugin): finalize reverse proxy support

packages/pages/src/common/src/template/internal/loader.ts
The features.json generation was failing in some circumstances when unknown filetypes were being imported into the templates. This is only an issue when running `pages features` directly and does not affect the build process. It's possible we may want to just remove this feature altogether as its own command.
=> fix(dev): add additional filetypes to esbuild loader for features.json

packages/pages/src/dev/dev.ts, packages/pages/src/dev/server/ssr/getLocalData.ts
The updated `pages dev` called `pages generate features` then `yext pages generate-test-data` then `createServer()`.
However, `createServer()` calls `yext pages generate-test-data` in [server.ts:57](https://github.com/yext/pages/blob/8b3454f33a9ed35e2ebbf4455ad98eb9fa1cb2a1/packages/pages/src/dev/server/server.ts#L57)
The pages dev call is managed by `--noGenTestData` while the `createServer` call is managed by `--local` (ie a user would need both `--noGenTestData` and `--local` to disable generation).
This PR removes the `pages dev` call and leaves the original one in `createServer`.
=> fix(dev): duplicated generate-test-data

packages/pages/src/dev/server/middleware/indexPage.ts, packages/pages/src/dev/server/middleware/serverRenderRoute.ts, packages/pages/src/dev/server/middleware/serverRenderSlugRoute.ts, packages/pages/src/dev/server/server.ts, packages/pages/src/dev/server/ssr/getLocalData.ts
Support static page locales based on `features.json`
**`features.json` does not include key `locales` or `features.json` does not exist**
The dev server behaves as before, with default locale `en`.
**`features.json` includes `locales` with array length 1**
The dev server index page behaves as before, default locale is set to the locale in the `locales` array.
**`features.json` includes `locales` with array length >1**
The dev server index page includes a static page listing for each locale. The default local is set to the first locale in the `locales` array.
=> fix(dev): static page locale support

packages/pages/src/bin/spawn.ts, packages/pages/src/build/build.ts, playground/locations-site/sites-config/ci.json, playground/locations-site/sites-config/features.json, playground/multibrand-site/sites-config/ci.json, playground/multibrand-site/sites-config/sunglasses.oakley.com/ci.json, playground/multibrand-site/sites-config/sunglasses.rayban.com/ci.json, playground/multibrand-site/sites-config/sunglasses.rayban.com/features.json
PagesJS commands now throw error codes properly. Subsequent commands no longer get executed on failure.
Example with an error added in closeBundle
=> fix(plugin): fail platform build when PagesJS build fails (fix #347)

packages/pages/src/common/src/feature/stream.test.ts, packages/pages/src/common/src/feature/stream.ts, packages/pages/src/common/src/template/internal/types.ts, packages/pages/src/common/src/template/types.ts
Change the public type for `TemplateConfig.Stream.localization` 
to allow `{locales: [...]}` or `{primary: true}` 
but never `{primary: false}` or `{locales: [...], primary: true/false}`.
Under the hood, convert the public type to an internal type that always has `primary` defined with this behavior:
```localization: {} -> localization: {primary: true}
localization: {primary: true} -> localization: {primary: true}
localization: {locales: []} -> localization: {primary: true}
localization: {locales: ['fr']} -> localization: {locales: ['fr'], primary: false}
localization: {locales: ['fr'], primary: true} -> localization: {locales: ['fr'], primary: false}
```
Some of these inputs are not valid TS but we don't call `tsc` when we do `pages generate features` so they could exist.
Breaking …
=> feat(dev)!: do not require localization.primary:false

packages/pages/src/build/build.ts, packages/pages/src/dev/dev.ts, packages/pages/src/generate/ci/ci.ts, packages/pages/src/generate/features/features.ts, packages/pages/src/prod/prod.ts
Use command handlers that were used previously with Yargs.
As opposed to action written directly in command.
This also fixes 'useProdUrls' in dev.ts
Tested all commands and ran auto tests.
=> refactor: restore command handlers

packages/pages/src/vite-plugin/plugin.ts, playground/locations-site/sites-config/features.json, playground/multibrand-site/sites-config/sunglasses.oakley.com/features.json
A minor version [change](https://github.com/davidmyersdev/vite-plugin-node-polyfills/commit/abf35b8c0309b0d5fc43d5e51e037d4ee4f675e3#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R164) to vite-plugin-node-polyfill adds a dev-only polyfill because it always assumes dev. This breaks the build when generating features because window is undefined. This changes the globals to be polyfilled as "build".
=> fix(plugin): polyfill upgrade breaking build

.gitignore, packages/pages/src/dev/dev.ts, packages/pages/src/dev/server/middleware/constants.ts, packages/pages/src/dev/server/middleware/indexPage.ts, packages/pages/src/dev/server/server.ts, packages/pages/src/index.ts
This PR exports createServer as createDevServer, and adds a port CLI arg and also to createServer itself.
The main purpose of this is to address inconsistencies with spawning pages as a child process from within `@yext/studio`.
But I think these changes are also useful outside of that purpose.
J=SLAP-2885
TEST=manual
test that I can start up the playground/locations-site with a --port arg
test that I can import createDevServer in a separate package and start the pages dev server with it
=> feat(dev): export createServer and add --port arg

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/common/src/parsers/sourceFileParser.ts, packages/pages/src/common/src/parsers/templateConfigParser.ts, packages/pages/src/common/src/template/internal/types.ts, packages/pages/src/dev/server/ssr/generateTestData.ts, packages/pages/src/generate/features/features.ts, packages/pages/src/generate/templates/createTemplatesJson.ts, packages/pages/src/generate/templates/createTemplatesJsonFromModule.test.ts, packages/pages/src/generate/templates/createTemplatesJsonFromModule.ts, packages/pages/src/generate/templates/templates.ts, packages/pages/src/vite-plugin/build/closeBundle/closeBundle.ts, pnpm-lock.yaml
Previous to this change, we used esbuild to compile the templates into modules in order to pull off the config const. This led to various issues for people. It works fine with Vite since Vite does a lot of CJS/polyfill magic, but we weren't handling that with esbuild. This was overkill anyways as we only need to grab the config off of the templates, so compilation is irrelevant at this step.
=> fix(dev): use ts-morph to parse template configs

packages/pages/src/common/src/assets/getAssetsFilepath.ts
Running `pages generate templates` would fail when a config.yaml file existed but it was completely empty.
=> fix: empty yaml leads to parse error

packages/pages/src/generate/artifacts/createArtifactsJson.test.ts, packages/pages/src/generate/artifacts/createArtifactsJson.ts, packages/pages/src/generate/ci/ci.test.ts, packages/pages/src/generate/ci/ci.ts
Since ci.json is auto-generated, specifically the assets portion, there's no option for a user to manually set the static assets anymore. Now we include everything in the root of dist which is where Vite will dump those files.
=> feat(plugin): include static assets in platform

packages/pages/src/common/src/parsers/sourceFileParser.ts, packages/pages/src/util/processEnvVariables.test.ts, packages/pages/src/util/processEnvVariables.ts
Environment variable string need to be quoted normally (within templates and functions) but were being double quote escaped when running through ts-morph during feature/template.json generation.
=> fix(dev): env vars through ts-morph double quoted

packages/pages/src/upgrade/upgrade.ts
Adds a --noMigration flag for the upgrade script. With noMigration, upgrade will skip the migration to config.yaml and deletion of sites-config.
Tested manually on a local repo. Migration is skipped with the flag and still occurs when the flag is missing.
=> feat(dev): add noMigration flag for upgrade

packages/pages/src/dev/server/autoInit.ts, packages/pages/src/util/checkInstalled.test.ts, packages/pages/src/util/checkInstalled.ts, packages/pages/src/util/runSubprocess.ts
We can change the message to ask the user to install packages once the CLI package change is ready
=> feat(dev): better error message for CLI not installed

packages/pages/src/common/src/template/hydration.ts
Fixes #225.
To support this, we now encode the page props before injecting the JS bundle in the DOM and have the JS bundle decode the props before passing it to the `render` function that renders the page.
J=SUMO-5337
TEST=manual
In a test site, see that both `dev` and `build:serve` can successfully serve a page that is using a Content field with HTML in it that includes a `</script>` closing tag. Test in the platform as well and see the page has errors without this change, and renders properly with the fix.
=> fix(dev/plugin): support HTML in Content fields

packages/pages/src/common/src/template/internal/validateGetPathValue.ts, packages/pages/src/dev/server/ssr/getLocalData.ts, packages/pages/src/dev/server/ssr/propsLoader.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.ts
Fixes #423.
Now, we explicitly check for and throw an error with a more clear message if the `getPath` value is not a string.
J=SUMO-5458
TEST=manual
In a test site in dev mode, see that the index page does not include any pages with a non-string `getPath` value and console error is logged instead. In `--no-prod-url` mode, see that visiting an entity page with a non-string `getPath` value throws an error with the more specific message instead of `path2.split is not a function`. Running `yext pages build && yext pages render` locally, as well as page generation in the platform, will throw the clearer error for a non-string `getPath` rather than `n.split is not a function`.
=> fix(dev/plugin): clearer error for non-string getPath value

packages/pages/src/vite-plugin/build/closeBundle/functionMetadata.ts
Fixes https://github.com/yext/pages/issues/409.
This PR addresses the "Cannot find module" errors that were found when using imports from `deno.land` modules.  In the past, we were using ESBuild to build user files in a temp dir, then using the built file to get the default import name.  However, ESBuild was not able to resolve these `deno.land` imports and would throw errors. In order to resolve `http`/`https` imports, we would need a plugin for ESBuild (see "[Why this is not Recommended](https://esbuild.github.io/getting-started/#deno)").  I looked for an npm package that would provide ESBuild with a plugin to resolve these imports, however none of them seemed well established/stable enough to use.
Here are two I considered:
- [esbuild-plugin-cache](https://www.npmjs.com/package/esbuild- …
=> fix(plugin): address "Cannot find module" for deno module imports

packages/pages/package.json, pnpm-lock.yaml
[VULN-38471](https://yexttest.atlassian.net/browse/VULN-38471), [VULN-38486](https://yexttest.atlassian.net/browse/VULN-38486), [VULN-38487](https://yexttest.atlassian.net/browse/VULN-38487)
@babel/traverse version <7.23.2 have a critical vulnerability.
=> chore: remove babel

packages/pages/src/bundler.js
Fix the `watch` command in `packages/pages/package.json` so `npm run build` doesn't need to be manually run each time a change is made to see the effects in a linked test site. Previously, this command would throw an error.
J=SUMO-5462
TEST=manual
Check that `npm run build` still works as expected. Run `npm run watch` and see that changes are automatically picked up and trigger a rebuild.
=> fix: fix watch command

packages/pages/THIRD-PARTY-NOTICES, packages/pages/package.json, packages/pages/src/common/src/loader/esbuild.ts, packages/pages/src/common/src/parsers/sourceFileParser.ts, packages/pages/src/util/processEnvVariables.test.ts, packages/pages/src/util/processEnvVariables.ts, packages/pages/src/vite-plugin/build/closeBundle/serverlessFunctions.ts, pnpm-lock.yaml
This adds support for truly secret environment variables. Before this change we only supported _public_ environment variables that were prefixed with `YEXT_PUBLIC`.
=> feat(dev/plugin): support secrets

packages/pages/src/upgrade/pagesUpdater.ts
Successfully replaces imports in pages-starter-react-locations.
Note that this will not cover imports such as
import {tacos, fetch} from "@yext/pages/util"
It only replaces \nimport { fetch } from "@yext/pages/util"; which fixes the starter.
=> feat(dev): replace fetch imports in upgrade command

packages/pages/src/upgrade/pagesUpdater.ts
Adds supported engines to package.json
```
"engines": {
"node": "^18.0.0 || >=20.0.0"
},
```
=> feat: add node engines to upgrade script

packages/pages/src/vite-plugin/build/closeBundle/manifest.ts
With the upgrade to Vite 5 they [moved](https://vitejs.dev/guide/migration#manifest-files-are-now-generated-in-vite-directory-by-default) where the manifest file lives during build. Before this fix a prod build was missing all CSS.
=> fix(plugin): manifest not created correctly

packages/pages/src/vite-plugin/build/closeBundle/functionMetadata.ts
The platform allows "main" exports and reads them specifically from the /functions folder (meaning that they shouldn't be defined in functionMetadata.json...only default exports go in there). Since platform allows it, we should too.
Additionally, function errors will now properly fail the build instead of continuing on.
=> fix(plugin): allow "main" function exports and actually fail the build

packages/pages/src/upgrade/migrateConfig.ts, packages/pages/src/upgrade/pagesUpdater.ts
Tested manually on starter.
Config.yaml ends up with npm run build as the build command.
package.json has build instead of "build:local": "pages build"
npm run prod and npm run dev work as expected.
=> feat(dev): upgrade script replaces build:local with build

packages/pages/src/upgrade/pagesUpdater.ts
Upgrades search-ui-react and search-headless-react if they are present.
Adds carets to upgraded version when getting the latest. If the version is provided in the helper, 
use the version as given.
=> feat(dev): upgrade search-ui-react and search-headless-react

packages/pages/src/util/dynamic.tsx, packages/pages/src/util/index.ts
Adds a `dynamic` util, similar to [next/dynamic](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic).  Its purpose is to support dynamically imported modules, similar to React lazy/suspense, but works with React 17.
=> feat(util): add dynamic function

packages/pages/package.json, packages/pages/src/upgrade/pagesUpdater.ts
Versions of Node 20 before 20.2.0 led to build errors `Unexpected early exit.`
=> fix(plugin): make min Node 20 version 20.2.0

packages/pages/src/dev/server/middleware/serverRenderRoute.ts, packages/pages/src/dev/server/middleware/serverRenderSlugRoute.ts
The locale was not sent through to transformIndexHtml, making the original request remain cached by the dev server. If you used a locale query param in one request and then removed it (or vice versa) you would never see the updated data.
=> fix(dev): locale query params not part of request

packages/pages/src/dev/server/middleware/indexPage.ts, packages/pages/src/dev/server/ssr/getLocalData.ts
Prior to this change the index page urls would show the slug when using local urls which was confusing since the actual urls have the format /[template-name]/[external-id] (and optional ?locale= query param if not ‘en’). We now show the actual url.
=> fix(dev): index page urls using `--no-prod-url`

packages/pages/docs/api/pages.templateconfig.alternatelanguagefields.md, packages/pages/docs/api/pages.templateconfig.md, packages/pages/etc/pages.api.md, packages/pages/package.json, packages/pages/src/common/src/feature/features.ts, packages/pages/src/common/src/template/internal/types.ts, packages/pages/src/common/src/template/types.ts, pnpm-lock.yaml
`alternateLanguageFields` causes page generations to take much longer, so it was deemed as unsupported for new accounts (generations will outright fail). Some accounts are still grandfathered in, but there are alternate solutions that can be used.
=> chore(dev): deprecate alternateLanguageFields

packages/pages/src/upgrade/pagesUpdater.test.ts, packages/pages/src/upgrade/pagesUpdater.ts
Moves all named imports from both `@yext/components-tsx-maps` and `@yext/components-tsx-geo` to `@yext/pages-components`. Also removes those imports from package.json.
=> feat(upgrade): move imports from components-tsx-maps/geo

packages/pages/src/upgrade/migrateConfig.test.ts, packages/pages/src/upgrade/migrateConfig.ts
`siteStream` in config.yaml only has four fields that we now explicitly set. Before this change we used the spread operator on the old config which brought in things not used in config.yaml, such as `source`.
=> fix(upgrade): siteStream conversion now sets specific fields

packages/pages/src/upgrade/upgrade.ts
The markdown warning check was never happening because we rewrote the imports that it's looking for before this check was executed.
=> fix(upgrade): check for Markdown before updating imports

packages/pages/src/common/src/parsers/sourceFileParser.test.ts, packages/pages/src/common/src/parsers/sourceFileParser.ts
It seems there's not a better way to handle imports with ts-morph. I tried straight text copying, which works, but then the output format doesn't match what's expected. While this isn't a huge deal technically it made many test cases fail. I'm open to other ways to move imports over if there's a more robust option.
=> fix(plugin): alias imports not output in hydration files

packages/pages/etc/pages.api.md, packages/pages/src/common/src/template/hydration.ts, packages/pages/src/common/src/template/internal/_server.tsx, packages/pages/src/common/src/template/types.ts, packages/pages/src/dev/server/middleware/sendAppHTML.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.test.tsx, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/wrapper.ts
This reworks the exports of _server.tsx. According to [this](https://github.com/vitejs/vite/pull/15345#issuecomment-1855550194) transformIndexHtml should be called on the index.html (which is provided automatically) and not the entire result of calling render (after the server code is injected). It hasn’t actually posed a problem but I’d like to get ahead of it and make sure we’re doing it the right way. It really only affects local dev but it’s breaking since what’s exported from _server.tsx has changed.
_server.tsx is now expected to export 3 things:
```
export const render = async (pageContext: PageContext<any>) => {
const { Page, pageProps } = pageContext;
return ReactDOMServer.renderToString(<Page {...pageProps} />);
};
export const replacementTag = "";
export const indexHtml = …
```
=> fix(dev)!: rework _server.tsx

packages/pages/src/dev/server/middleware/sendAppHTML.ts
transformIndexHtml results in the client module imports looking like this:
`<script type="module" src="/@id/__x00__/location?html-proxy&amp;index=0.js"></script>`
Upon page refresh, because the client path is the same, the browser caches the response. This meant that when props changed, they weren't actually reflected. We now append a time to unique-ify the request to ensure that the latest props are always used.
The import now looks like this:
`<script type="module" src="/@id/__x00__/location61707256037383?html-proxy&amp;index=0.js"></script>`
=> fix(dev): cache bust client

packages/pages/src/common/src/project/structure.ts, packages/pages/src/dev/server/ssr/generateTestData.ts, packages/pages/src/upgrade/migrateConfig.ts
siteStream was only being passed through to generate-test-data when there was a sites-config/site-stream.json file. This ensures the same functionality when using config.yaml.
Fixes https://github.com/yext/pages/issues/483
=> fix(dev): include siteStream from config.yaml in GTD

packages/pages/src/build/build.ts, packages/pages/src/common/src/project/structure.ts, packages/pages/src/dev/dev.ts, packages/pages/src/generate/artifacts/artifacts.ts, packages/pages/src/generate/ci/ci.ts, packages/pages/src/generate/features/features.ts, packages/pages/src/prod/prod.ts, packages/pages/src/scaffold/modules/generate.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/wrapper.ts, packages/pages/src/vite-plugin/modules/plugin.ts, packages/yext-function/manifest.ts
`npm run prod -- --scope myScope` works w/ myScope in templates, modules, and both. npm run build and dev work as expected as well. Double checked scaffolding supported scope still too. 
scope means files in both myScope and src/... are built and used. Without the scope being set, the files in myScope are not used. If a file is in myScope and in src/... (with same config name), the one in myScope should be used (if scope is set).
=> feat: support scope with modules

packages/pages/src/dev/server/ssr/generateTestData.ts
Fixes the following issues:
1. Not passing the --scope flag to the CLI GTD which is necessary for config v2 (we were only passing --hostname which works the same but only for config v1)
2. `slug` wasn't added to the --slugFields flag if no other alternate slugFields were used
3. Filters out static templates so we can actually find the correct document. Currently, the --featuresConfig flag is not honored by the CLI so static template document data is coming back when it shouldn't. This is a workaround for that.
=> fix(dev): adjust GTD logic and pass scope

packages/pages/src/dev/server/middleware/serveHttpFunction.ts, packages/pages/src/util/logError.ts
A serverless function that uses an undefined env var would result in the dev server crashing. This fixes that.
=> fix(dev): serverless functions dev server crash

packages/pages/src/upgrade/pagesUpdater.ts
Verified that upgrade script works correctly and sets the engine to 18.4.0
=> feat(dev): upgrade script uses engine 18.4.0

packages/pages/src/dev/server/ssr/generateTestData.ts
Documents by slug weren't correctly being found due to a bug using map instead of filter.
=> fix(dev): filtering documents by slug

packages/pages/src/dev/server/middleware/serverRenderRoute.ts, packages/pages/src/dev/server/middleware/serverRenderSlugRoute.ts, packages/pages/src/dev/server/ssr/findMatchingStaticTemplate.ts, packages/pages/src/dev/server/ssr/findTemplateModuleInternal.ts, packages/pages/src/dev/server/ssr/getLocalData.ts
This change speeds up the dev server page load performance on subsequent page refreshes/HMR changes by caching a mapping of templateName to templateFilepath. This allows us to find the templates much more quickly. Beforehand, we were iterating through and loading every template on each requests.
This caching also has the added benefit of making the Node memory less spikey (and with less GC) because less modules are loaded now.
=> perf(dev): speed up page loads and alleviate memory pressure

packages/pages/docs/api/pages.getredirects.md, packages/pages/etc/pages.api.md, packages/pages/src/common/src/redirect/types.ts, packages/pages/src/common/src/template/types.ts, packages/pages/src/vite-plugin/build/buildStart/rendering/templateUtils.ts
Allows the user to pass in either RedirectSource {source: string, statusCode: int}[] or string[] for GetRedirects
The Yext CLI has not been updated to accept the new type yet, so this currently only works for string[]
=> feat(plugin): add support for statusCode to getRedirects

packages/pages/src/common/src/project/structure.ts
Manifest is no longer being used after the changes in https://github.com/yext/pages/pull/517.
=> refactor: remove manifest check from getTemplatePaths

packages/pages/src/util/env.test.ts, packages/pages/src/util/env.ts
Instead of requiring a list of prod domains to check against, isProduction now uses the IS_PRODUCTION global variable which is guaranteed to be correct as it's injected by the serving layer.
=> feat(dev/plugin): update isProduction logic

packages/pages/src/util/viteConfig.ts, packages/pages/src/vite-plugin/modules/plugin.ts, packages/pages/src/vite-plugin/serverless-functions/plugin.ts
Tested and confirmed it does use the user's build.rollupOptions.external when I add that to the `vite.config.js`
Tested w/ both the problem build (a serverless func repo) and a modules repo.
`configFile: false` should remain or else it'll get stuck in infinite loop of yext plugin.
=> fix(plugin): use the user's vite.config

packages/pages/src/dev/server/middleware/getContentType.ts
The mime-type library returns "application/json" when passed a value of "map" (also true for "json"). Don't use the library if there is no extension and instead default to "text/html".
This bug presented itself when someone used a slug value of "map" and the page rendered as raw html.
=> fix(dev): don't lookup mime type unless there's an extension

packages/pages/docs/api/pages.templateconfig.additionalproperties.md, packages/pages/docs/api/pages.templateconfig.md, packages/pages/etc/pages.api.md, packages/pages/src/common/src/feature/features.ts, packages/pages/src/common/src/template/internal/types.ts, packages/pages/src/common/src/template/types.ts
[SUMO-6228](https://yexttest.atlassian.net/browse/SUMO-6228?atlOrigin=eyJpIjoiYWNjMjk0YzhjMDQxNDk0Yjk4NDg2MGE0MjhiMTkxYTkiLCJwIjoiaiJ9)
Tested by building with 'pnpm -r run build'
=> refactor: change the type of additionalProperties in TemplateConfig to 'Record<string, any>'

README.md, packages/pages/src/util/README.md, packages/pages/src/util/index.ts, packages/pages/src/util/useDocument.tsx
Migrates useDocument from the VE starter to this repo. Also moves DocumentProvider. Documentation added to README.md
=> feat(util): add useDocument hook

packages/pages/src/common/src/template/hydration.ts, packages/pages/src/dev/server/middleware/sendAppHTML.ts, packages/pages/src/generate/features/features.ts, packages/pages/src/generate/templates/createTemplatesJson.ts, packages/pages/src/generate/templates/templates.ts
Adds the templatesJson to the header so that we can access it in the Visual Editor.
Tested locally and verified that the templatesJson was present in a script tag in the header.
Also verified that `npm run prod` still works as expected and the templatesJson is not present.
=> feat(dev): add pageSets to global variable in header in dev mode

packages/pages/src/common/src/parsers/puckConfigParser.ts, packages/pages/src/scaffold/template/generate.ts
Tested and it works immediately after scaffolding but you do see kinda long list of warnings about conflicting peer dependencies, like: 
npm WARN 
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/utils@5.62.0
npm WARN   node_modules/@yext/visual-editor/node_modules/@yext/eslint-config/node_modules/eslint-config-react-app/node_modules/eslint-plugin-testing-library/node_modules/@typescript-eslint/utils
npm WARN     @typescript-eslint/utils@"^5.58.0" from eslint-plugin-testing-library@5.11.1
npm WARN     node_modules/@yext/visual-editor/node_modules/@yext/eslint-config/node_modules/eslint-config-react-app/node_modules/eslint-plugin-testing-library
=> fix(scaffold): edit puck version

packages/pages/src/vite-plugin/serverless-functions/plugin.ts
https://github.com/yext/pages/pull/524 added support for merging a user's vite.config.js during the serverless function build process. However, other items in the config can cause the build to fail. Limit serverless functions to be merged **only** with  the build.rollupOptions.external option.
=> fix(plugin): don't merge the entire user vite.config.js

packages/pages/src/dev/server/server.ts, packages/pages/src/scaffold/modules/templates.ts
Updates the module template to reflect newer changes of the AnalyticsProvider of pages-components. Also adds React as an import to fix TS. Finally, simplifies some of the module dev server code.
=> fix(scaffold): update module template

packages/pages/src/scaffold/modules/generate.ts, packages/pages/src/scaffold/modules/templates.ts
Updating how scoping tailwind logic for modules work. Confirmed it works in local dev, local prod, and platform. Tested with multiple modules on one page as well ensuring that tailwind styles don't leak into inserted page.
Instead of needing 
```
.tailwind {
@tailwind base;
}
```
in the index.css we are using the `tailwindcss-scoped-preflight` library in the `tailwind.config.ts ` to scope it to `tailwind tw-${moduleName}`.
So the module component will need to be wrapped by  
```
<div className="tailwind tw-${moduleName}">
Module
</div>
```
=> fix(modules): update scaffold tailwind 

.github/workflows/main.yml
Ubuntu 20.04 for Github Actions is being deprecated and will be fully unsupported on 2025-04-01. Update our semgrep action to the latest version.
=> chore: update main.yml to use ubuntu-latest

packages/pages/src/common/src/template/loader/loader.test.ts, packages/pages/src/common/src/template/loader/loader.ts, packages/pages/src/dev/server/middleware/sendAppHTML.ts, packages/pages/src/dev/server/ssr/generateTestData.ts, packages/pages/src/generate/templates/createTemplatesJson.test.ts, packages/pages/src/generate/templates/createTemplatesJson.ts
In https://github.com/yext/pages/pull/564, the in-platform page sets were filtered in loader.ts, which removed them from both the manifest.json and features.json. They are still needed in manifest.json so page generation was failing. This change only removes them from features.json. 
Tested in-platform and confirmed that in platform page set pages generate successfully and the static pages are no longer generated.
=> fix: correctly ignore templates marked for in platform page sets

.github/workflows/generate_markdown_files.yml
So `github.head_ref` is only populated on pull workflows, generate_markdown is a push workflow, so ref was always empty anyways. 
The vulnerability was worried about:
> Using variable interpolation `$...` with `github` context data in a `run:` step could allow an attacker to inject their own code into the runner. This would allow them to steal secrets and code. `github` context data can have arbitrary user input and should be treated as untrusted. Instead, use an intermediate environment variable with `env:` to store the data and use the environment variable in the `run:` script. Be sure to use double-quotes the environment variable, like this: "$ENVVAR".
which is valid and their suggested solution would've worked if we had ref or need the ref
=> fix: workflow vulnerability

packages/pages/src/dev/server/ssr/generateTestData.ts
prepareJsonForCmd was stringifying the undefined variable so the `if (siteStream)` check was returning true.
=> fix(dev): siteStream not properly null checked

.github/workflows/generate_markdown_files.yml
Required fix for vulnerability in addition to #573. Did not realize it was required because: 
> Semgrep updated their run-shell-injection rule a while back to treat {{steps. ... .outputs. ...}}  — e.g. this file's outputs.pushed — as untrusted inputs that should be loaded in as Environment Variables through the env: option. Unfortunately, they did not update the description of their rule, so our ticket description was incomplete.
=> fix: additional workflow change

packages/plugins/slugManager/manager.ts
A prior [fix](https://github.com/yext/pages/pull/547) attempted this but had a bug. The fix is to prevent making api requests with unbounded entities. Unfortunately, the previous attempt never checked length so when the array was empty the condition never hit.
=> fix(pages-plugins): slugmanager unbounded entity request bug

packages/pages/etc/pages.api.md, packages/pages/src/dev/dev.ts, packages/pages/src/dev/server/server.ts
Runs `pages generate features`/`pages generate templates` after initializing the vite server so that vite plugins run before generation.
Confirmed in the VE starter that the edit static page was generated.
Confirmed in a non-VE starter that entity and static pages were generated and the `--noGenFeatures` flag worked.
=> refactor(dev): generate templates.json after vite initialization
